### ISSUE TITLE
Replace Unicode / LaTeX conversion table with R script

### ISSUE THREAD

**Issue by nanxstats** [Merck/r2rtf#218]
Suggestion from @yihui: https://github.com/Merck/r2rtf/pull/217/files?diff=unified&w=0#r1564779269

The goal is to put the `unicode_latex` variable in an R script, to replace the current binary form stored in `R/sysdata.rda`.

This would also avoid the need of the `globalVariables()` call for `unicode_latex` as a hack to bypass R CMD check notes.

**Comment by elong0527** [comment]
Based on our discussion, it might trigger issues with special characters. Would consider to keep it as is.

**Comment by yihui** [comment]
Special characters written in the form `\Uxxxx` should be fine for R CMD check. Alternatively, they can be encoded to integers via `utf8ToInt()` and converted back to UTF-8 via `intToUtf8()`. Technically I guess the problem is solvable, but I understand it's no big deal, so I'm okay with leaving it alone.
