### ISSUE TITLE
rtf_page breaks before 42 rows

### ISSUE THREAD

**Issue by nielsonc** [Merck/r2rtf#5]
A multi-page, portrait-oriented table has page breaks after 15-24 rows rather than including 42 rows per page. Specifying nrow=42 results in a longer first page, but subsequent pages still end after ~15 rows. No page_by or group_by options are specified.

**Comment by elong0527** [comment]
Could you provide an [reprex](https://reprex.tidyverse.org/) example?

the `iris` example below works as expected from my end

```
library(dplyr)
library(r2rtf)

iris %>% rtf_body() %>% rtf_encode() %>% write_rtf("tmp.rtf")
```

**Comment by nielsonc** [comment]
Yes, it seems to be an issue with long variable names. In my table, the names wrap. However, in the example below, even without wrapping, the long variable name seems to make the table end too short.

```
library(dplyr)
library(r2rtf)
library(stringr)


iris %>%
  rtf_page() %>%
  rtf_body() %>%
  rtf_encode() %>%
  write_rtf("tmp1.rtf")

iris2 <- iris

# make one of the variable names long
iris2$Species <- str_replace_all(iris2$Species, "setosa", "setosa setosa setosa")

# table ends too short (specifically when page contains long variable names)
iris2 %>%
  rtf_page() %>%
  rtf_body() %>%
  rtf_encode() %>%
  write_rtf("tmp2.rtf")

# try to lengthen with nrow = 45, but table stays short
iris2 %>%
  rtf_page(nrow = 45) %>%
  rtf_body() %>%
  rtf_encode() %>%
  write_rtf("tmp3.rtf")

```

**Comment by elong0527** [comment]
Thanks for the input. To properly estimate number of rows in each page, we need to approximate the total width of each cell to determine how many rows we need for each line of the data.

You will see how it works in RTF by running the code

```
iris2 <- iris

# make one of the variable names long
iris2$Species <- str_replace_all(iris2$Species, "setosa", "setosa setosa setosa setosa")

# table ends too short (specifically when page contains long variable names)
iris2 %>%
  rtf_page() %>%
  rtf_body() %>%
  rtf_encode() %>%
  write_rtf("tmp1.rtf")
```

We used a conservative way because the default font is not monogram. Therefore, the issue in your example code could happen.

Please try two potential solutions below. The package needs to be re-installed from github for Option 1. 

```
devtools::load_all()

library(dplyr)
library(stringr)

iris2 <- iris
# make one of the variable names long
iris2$Species <- str_replace_all(iris2$Species, "setosa", "setosa setosa setosa")
```

## Option 1

* use the newly added argument `cell_nrow` to specify number of rows required for each data cell. 
 
```
# table ends too short (specifically when page contains long variable names)
iris2 %>%
  rtf_page() %>%
  rtf_body(cell_nrow = 1) %>%
  rtf_encode() %>%
  write_rtf("tmp2.rtf")
```
* Note: `cell_nrow` allow you to set value for each cell. You can find it by checking the attributes of the data
```
tmp1 <- iris2 %>%
  rtf_page() %>%
  rtf_body(cell_nrow = 1)

attr(tmp1, "cell_nrow")
```

## Option 2

* increate cell width. 

```
# You will need to define col_header to make the column header width displayed properly
iris2 %>%
  rtf_page() %>%
  rtf_colheader(paste0(names(iris), collapse = "|"), col_rel_width = c(rep(1,4),2)) %>%
  rtf_body(col_rel_width = c(rep(1,4),2)) %>%
  rtf_encode() %>%
  write_rtf("tmp3.rtf")
```
